name: homer_makeucscfile
description: Annotate peaks with HOMER suite
keywords:
  - annotations
  - peaks
  - bedgraph
tools:
  - homer:
      description: |
        HOMER (Hypergeometric Optimization of Motif EnRichment) is a suite of tools for Motif Discovery and next-gen sequencing analysis.
      documentation: http://homer.ucsd.edu/homer/
      doi: 10.1016/j.molcel.2010.05.004.
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tagDir:
      type: directory
      description: "The 'Tag Directory'"
      pattern: "tagDir"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bedGraph:
      type: file
      description: The generated bedGraph
      pattern: "tag_dir/*ucsc.bedGraph.gz"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@EMiller88"
